# **45장 프로미스**

- [**45장 프로미스**](#45장-프로미스)
  - [**들어가며 🎈**](#들어가며-)
  - [**REST API의 구성**](#rest-api의-구성)
    - [**콜백 헬**](#콜백-헬)
    - [**에러 처리의 한계**](#에러-처리의-한계)
  - [**프로미스의 생성**](#프로미스의-생성)
  - [**프로미스의 후속 처리 메서드**](#프로미스의-후속-처리-메서드)
    - [**Promise.prototype.then**](#promiseprototypethen)
    - [**Promise.prototype.catch**](#promiseprototypecatch)
    - [**Promise.prototype.finally**](#promiseprototypefinally)
  - [**프로미스의 에러처리**](#프로미스의-에러처리)
  - [**프로미스 체이닝**](#프로미스-체이닝)

<br>

## **들어가며 🎈**

본 정리글은 이웅모강사님의 모던 자바스크립트 Deep Dive를 공부하고 습득하기 위해 제 나름대로 정리한 글 입니다. 보다 상세한 정보를 원하신다면 해당 서적을 참고하시길 바랍니다.

비동기 처리를 위한 하나의 패턴으로 콜백 함수를 사용한다. 하지만 전통적인 콜백 패턴은 콜백 헬로 인해 가독성이 나쁘고 비동기 처리 중 발생한 에러의 처리가 곤란하며 여러 개의 비동기 처리를 한번에 처리하는 데도 한계가 있다.

ES6에서는 비동기 처리를 위한 또 다른 패턴으로 프로미스(_Promise_)를 도입했다. 프로미스는 전통적인 코백 패턴이 가진 단점을 보완하며 비동기 처리 시점을 명확하게 표현할 수 있다는 장점이 있다.

## **REST API의 구성**

### **콜백 헬**

```javascript
// GET 요청을 위한 비동기 함수
const get = (url) => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      console.log(JSON.parse(xhr.response));
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

get('https://jsonplaceholder.typicode.com/posts/1');
/*
{
  userId: 1,
  id: 1,
  title: 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
  body: 'quia et suscipit\nsuscipit recusandae consequuntur …strum rerum est autem sunt rem eveniet architecto'
} 
 */
```

- 비동기 함수(예제의 get 함수)
  - 함수 내부에 비동기로 동작하는 코드를 포함한 함수를 말한다.
  - 비동기 함수 내부의 비동기로 동작하는 코드는 비동기 함수가 종료된 이후에 완료된다.
  - 비동기 함수 내부의 비동기로 동작하는 코드에서 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하면 기대한 대로 동작하지 않는다.

```javascript
let todos;

const get = (url) => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      todos = JSON.parse(xhr.response);
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

get('https://jsonplaceholder.typicode.com/posts/1');
console.log(todos); // undefined
```

- 비동기 함수는 비동기 처리 결과를 외부에 반환할 수 없고, 상위 스코프의 변수에 할당할 수도 없다.
- 비동기 함수 처리 결과에 대한 후속 처리는 비동기 함수 내부에서 수행해야 한다.
- 비동기 처리 결과에 대한 후속 처리를 수행하는 콜백 함수를 전달하는 것이 일반적이다.

```javascript
// 비동기 처리가 성공하면 호출될 콜백 함수와
// 비동기 처리가 실패하면 호출될 콜백 함수를 전달
const get = (url, successCallback, failureCallback) => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      successCallback(JSON.parse(xhr.response));
    } else {
      failureCallback(xhr.status);
    }
  };
};

// id가 1인 post를 취득
get('https://jsonplaceholder.typicode.com/posts/1', console.log, console.error);
/* 
{
  userId: 1,
  id: 1,
  title: 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
  body: 'quia et suscipit\nsuscipit recusandae consequuntur …strum rerum est autem sunt rem eveniet architecto'
}
*/
```

- 콜백 함수 호출이 중첩되어 복잡도가 높아지는 현상이 발생, 콜백 헬<sup>callback hell</sup>이라 한다.

```javascript
const get = (url, callback) => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      // 서버의 응답을 콜백 함수에 전달하면서 호출하여 응답에 대한 후속 처리를 한다
      callback(JSON.parse(xhr.response));
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

const url = 'https://jsonplaceholder.typicode.com';
// id가 1인 post의 userId를 취득
get(url + '/posts/1', ({ userId }) => {
  console.log(userId);
  // post의 userID를 사용하여 user 정보를 취득
  get(url + '/users/' + userId, (userInfo) => {
    console.log(userInfo); // {id: 1, name: "Leanne Graham", username: "Bret", ...}
  });
});
```

```javascript
get('/step1', (a) => {
  get(`/step2/${a}`, (b) => {
    get(`/step3/${c}`, (c) => {
      get(`/step3/${c}`, (c) => {
        console.log(d);
      });
    });
  });
});
```

<br>

### **에러 처리의 한계**

- 콜백 패턴의 문제점 중에서 가장 심각한 것은 에러 처리가 곤란하다는 것이다.

```javascript
try {
  setTimeout(() => {
    throw new Error('Error!');
  }, 1000);
} catch (e) {
  // 에러를 캐치하지 못한다
  console.error('캐치한 에러', e);
}
```

> 📄 **try...catch...finally 문**
>
> `try...catch...finally` 문은 에러 처리를 구현하는 방법이다. `try...catch...finally` 문을 실행하면 먼저 `try` 코드 블록이 실행된다. 이때 `try` 코드 블록에 포함된 문 중에서 에러가 발생하면 해당 에러는 `catch` 문의 `err` 변수에 전달되고 `catch` 코드 블록이 실행된다. `finally` 코드 블록은 에러 발생과 상관없이 반드시 한 번 실행된다. `try...catch...finally` 문으로 에러를 처리하면 프로그램이 강제 종료되지 않는다.

- 에러는 호출자<sup>caller</sup> 방향으로 전파된다. 즉 콜 스택의 아래 방향(실행 중인 실행 컨텍스트가 푸시되기 직전에 푸시된 실행 커텍스트 방향)으로 전파된다.
- `setTimeout` 함수의 콜백 함수를 호출한 것은 `setTimeout` 함수가 아니다.
- `setTimeout` 함수의 콜백 함수가 발생시킨 에러는 `catch` 블록에서 캐치되지 않는다.
- 이를 극복하기 위해 프로미스<sup>Promise</sup>가 도입되었다.

<br>

---

## **프로미스의 생성**

- `Promise` 생성자 함수를 `new` 연산자와 함꼐 포출하면 프로미스를 생성한다.
- 호스트 객체가 아닌 ECMAScript 사양에 정의된 표준 빌트인 객체다.
- `Promise` 생성자 함수는 비동기 처리를 수행할 콜백 함수(ECMAScript 사양에서는 execurator 함수라 부른다)를 인수로 전달받는데 이 콜백 함수는 `resolve`와 `reject` 함수를 인수로 전달받는다.

```javascript
// 프로미스 생성
const promise = new Promise((resolve, reject) => {
    // Promise 함수의 콜백 함수 내부에서 비동기 처리를 수행한다.
    if (/* 비동기 처리 성공 */) {
        resolve('result');
    } else { /* 비동기 처리 실패 */
        reject('failure reason');
    }
});
```

- 비동기 처리가 성공하면 콜백 함수의 인수로 전달받은 `resolve` 함수를 호출하고, 비동기 처리가 실패하면 `reject` 함수를 호출한다.

```javascript
const promiseGet = (url) => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open('GET', url);
    xhr.send();

    xhr.onload = () => {
      if (xhr.status === 200) {
        resolve(JSON.parse(xhr.response));
      } else {
        reject(new Error(xhr.status));
      }
    };
  });
};

// promiseGet 함수는 프로미스를 반환한다.
promiseGet('https://jsonplaceholder.typicode.com/posts/1');
```

<center>프로미스의 상태 정보</center> | <center>의미</center> | <center>상태 변경 조건</center>
--- | --- | ---
pending | 비동기 처리가 아직 수행되지 않은 상태 | 프로미스가 생성된 직후 기본 상태
**fulfilled** | 비동기 처리가 수행된 상태(성공) | `resolve` 함수 호출
**rejected** | 비동기 처리가 수행된 상태(실패) | `reject` 함수 호출

- 프로미스는 pending 상태에서 fulfilled 상태 혹은 rejected 상태, 즉 settled 상태로 변화할 수 있다.
- settled 상태가 되면 더는 다른 상태로 변화할 수 없다.
- 프로미스는 비동기 처리 상태와 더불어 비동기 처리 결과도 상태로 갖는다.

```javascript
const fulfilled = new Promise((resolve) => resolve(1));
```

```javascript
const rejected = new Promise((_, reject) =>
  reject(new Error('error occurred'))
);
```

- **프로미스는 비동기 처리 상태와 처리 결과를 관리하는 객체다.**

<br>

---

## **프로미스의 후속 처리 메서드**

- 프로미스는 후속 메서드 `then`, `catch`, `finally`를 제공한다.
- 프로미스의 비동기 처리 상태가 변화하면 후속 처리 메서드에 인수로 전달한 콜백 함수가 선택적으로 호출된다.
- 이때 후속 처리 메서드의 콜백 함수에 프로미스의 처리 결과가 인수로 전달된다.

<br>

### **Promise.prototype.then**

- `then` 메서드는 두 개의 콜백 함수를 인수로 전달 받는다.
  - 첫 번째 콜백 함수(성공 처리 콜백 함수)는 프로미스가 fulfilled 상태가 되면 호출된다. 이때 콜백 함수는 프로미스의 비동기 처리 결과를 인수로 전달받는다.
  - 두 번째 콜백 함수(실패 처리 콜백 함수)는 프로미스가 rejected 상태가 되면 호출된다. 이때 콜백 함수는 프로미스의 에러를 인수로 전달받는다.

```javascript
// fulfilled
new Promise((resolve) => resolve('fulfilled')).then(
  (v) => console.log(v),
  (e) => console.error(e)
); // fulfilled

// rejected
new Promise((_, reject) => reject(new Error('rejected'))).then(
  (v) => console.log(v),
  (e) => console.error(e)
); // Error: rejected
```

- `then` 메서드는 언제나 프로미스를 반환한다.
- 만약 `then` 메서드의 콜백 함수가 프로미스를 반환하면 그 프로미스를 그대로 반환하고, 콜백 함수가 프로미스가 아닌 값을 반환하면 그 값을 암묵적으로 `resolve` 또는 `reject` 하여 프로미스를 생성해 반환한다.

<br>

### **Promise.prototype.catch**

- `catch` 메서드는 한 개의 콜백 함수를 인수로 전달받는다.
- `catch` 메서드의 콜백 함수는 프로미스가 rejected 상태인 경우만 호출된다.

```javascript
// rejected
new Promise((_, reject) => reject(new Error('rejected'))).catch((e) =>
  console.error(e)
);
```

- `catch` 메서드는 `then`과 동일하게 동작한다. 언제나 프로미스를 반환한다.

<br>

### **Promise.prototype.finally**

- `finally` 메서드는 한 개의 콜백 함수를 인수로 전달받는다.
- `finally` 메서드의 콜백 함수는 프로미스의 성공 또는 실패와 상관없이 무조건 한 번 호출된다.
- 프로미스의 상태와 상관없이 공통적으로 수행해야 할 처리 내용이 있을 때 유용하다.
- `catch`와 `then`처럼 언제나 프로미스를 반환한다.

```javascript
new Promise(() => {}).finally(() => console.log('finally'));
```

```javascript
// 프로미스로 구현한 비동기 함수 get을 사용해 후속 처리 구현
const promiseGet = (url) =>
  new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open('GET', url);
    xhr.send();

    xhr.onload = () => {
      if (xhr.status === 200) {
        resolve(JSON.parse(xhr.response));
      } else {
        reject(new Error(xhr.status));
      }
    };
  });

promiseGet('https://jsonplaceholder.typicode.com/posts/1')
  .then((res) => console.loe(res))
  .catch((err) => console.log(err))
  .finally(() => console.log('Bye!'));
```

<br>

---

## **프로미스의 에러처리**

- 프로미스는 에러를 문제없이 처리할 수 있다.

```javascript
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1';

// 부적절한 URL이 지정되었기 때문에 에러가 발생한다.
promiseGet(wrongUrl).then(
  (res) => console.log(res),
  (err) => console.error(err)
); // Error: 404
```

- 비동기 처리에서 발생한 에러는 프로미스의 후속 처리 메서드 `catch`를 사용해 처리할 수도 있다.

```javascript
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1';

// 부적절한 URL이 지정되었기 때문에 에러가 발생한다.
promiseGet(wrongUrl)
  .then((res) => console.log(res))
  .catch((err) => console.error(err));
```
- `catch` 메서드를 모든 `then` 메서드를 호출한 이후에 호출하면 비동기 처리에서 발생한 에러(rejected 상태)뿐만 아니라 `then` 메서드 내부에서 발생한 에러까지 모두 캐치할 수 있다.
- 에러처리는 가독성이 좋은 `catch` 메서드에서 하는 것을 권장한다.

<br>

---

## **프로미스 체이닝**


